name: SynApp OHIF Viewer Develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build, Test, and Build Docker Image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --ci --watchAll=false

      - name: Build the application
        run: yarn build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/imhotep-synapp/synapp-ohif-viewer:develop . --platform linux/amd64
          docker push ghcr.io/imhotep-synapp/synapp-ohif-viewer:develop

  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build # Ensure deploy runs after build completes
    steps:
      - name: SSH into server and update Docker image
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/synapp-docker-services/
            docker compose --env-file=.env.dev stop synapp-ohif-viewer
            docker rmi -f ghcr.io/imhotep-synapp/synapp-ohif-viewer:develop
            docker compose --env-file=.env.dev --profile=init up -d synapp-ohif-viewer
